src/Entity/BlogCategory.php
<?php
/**
 * User: Oscar Sanchez
 * Date: 19/8/20
 */

namespace App\Entity;


use App\Image\ImageManipulator;
use App\Util\StringUtil;
use App\Util\UploadsUtil;
use Symfony\Component\HttpFoundation\File\File;

class BlogCategory
{
    const UPLOAD_SUBDIRECTORY = 'blog_category';
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $subtitle;

    /**
     * @var string
     */
    private $content;

    /**
     * @var string
     */
    private $metaTitle;

    /**
     * @var string
     */
    private $metaDescription;

    /**
     * @var string
     */
    private $image;

    /**
     * @var User
     */
    private $user;

    /**
     * BlogCategory constructor.
     * @param string $title
     * @param string $subtitle
     * @param string $content
     * @param string $metaTitle
     * @param string $metaDescription
     * @param File $image
     * @param User $user
     */
    public function __construct(string $title,
                                string $subtitle,
                                string $content,
                                string $metaTitle,
                                string $metaDescription,
                                File $image,
                                User $user)
    {
        $this->title = $title;
        $this->subtitle = $subtitle;
        $this->content = $content;
        $this->metaTitle = $metaTitle;
        $this->metaDescription = $metaDescription;

        if ($image) {
            $this->addImage($image);
        }
        $this->user = $user;
    }

    /**
     * @param string $file
     */
    public function addImage(string $file)
    {
        if (isset($this->image)) {
            $this->deleteImage();
        }

        $fileName = $this->title . '-' . uniqid() . '.';
        $extension = ImageManipulator::getExtensionTmpFile($file);
        $fileOutput = UploadsUtil::getDirectoryPrivateUploadsPath(self::UPLOAD_SUBDIRECTORY) . '/' . $fileName;

        ImageManipulator::generateFullCover($fileOutput, $file);

        $this->image = UploadsUtil::getPublicPath(self::UPLOAD_SUBDIRECTORY) . '/' . $fileName . $extension;
    }

    /**
     *
     */
    public function deleteImage(): void
    {
        try {
            UploadsUtil::delete(UploadsUtil::getDirectoryPath($this->image));

        } catch (\InvalidArgumentException $e) {
        }


        $this->image = null;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @return string
     */
    public function getSubtitle(): string
    {
        return $this->subtitle;
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @return string
     */
    public function getMetaTitle(): string
    {
        return $this->metaTitle;
    }

    /**
     * @return string
     */
    public function getMetaDescription(): string
    {
        return $this->metaDescription;
    }

    /**
     * @return string
     */
    public function getImage(): string
    {
        return $this->image;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * @param string $subtitle
     */
    public function setSubtitle(string $subtitle): void
    {
        $this->subtitle = $subtitle;
    }

    /**
     * @param string $content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * @param string $metaTitle
     */
    public function setMetaTitle(string $metaTitle): void
    {
        $this->metaTitle = $metaTitle;
    }

    /**
     * @param string $metaDescription
     */
    public function setMetaDescription(string $metaDescription): void
    {
        $this->metaDescription = $metaDescription;
    }

    /**
     * @param string $image
     */
    public function setImage(string $image): void
    {
        $this->image = $image;
    }

    public function getSlug()
    {
        return StringUtil::cleanString($this->title);
    }




}

src/Controller/BlogController.php
<?php
/**
 * User: Oscar Sanchez
 * Date: 19/8/20
 */

namespace App\Controller;


use App\Exception\BlogCategoryExceptionNotFound;
use App\Exception\PostNotFoundException;
use App\Exception\UserNotIsPropertyOfObjectException;
use App\Form\Type\BlogCategoryCreateType;
use App\Form\Type\BlogCategoryUpdateType;
use App\Form\Type\PostCreateType;
use App\Form\Type\PostUpdateType;
use App\Repository\BlogCategoryRepositoryInterface;
use App\Repository\PostRepositoryInterface;
use App\Repository\UserRepositoryInterface;
use App\Security\AuthUser;
use App\Service\DTO\BlogCategoryCreateDTO;
use App\Service\DTO\BlogCategoryDeleteDTO;
use App\Service\DTO\BlogCategoryUpdateDTO;
use App\Service\DTO\BlogQueryDTO;
use App\Service\DTO\PostCreateDTO;
use App\Service\DTO\PostDeleteDTO;
use App\Service\DTO\PostUpdateDTO;
use App\Service\Handler\BlogCategoryCreateHandler;
use App\Service\Handler\BlogCategoryDeleteHandler;
use App\Service\Handler\BlogCategoryUpdateHandler;
use App\Service\Handler\PostCreateHandler;
use App\Service\Handler\PostDeleteHandler;
use App\Service\Handler\PostUpdateHandler;
use App\Service\Query\BlogQuery;
use App\Session\TranslatableFlashBag;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{

    /**
     * @Route("/admin/blog/category/create", name="blog_category_create")
     * @param Request $request
     * @param BlogCategoryCreateHandler $handler
     * @param TranslatableFlashBag $flashBag
     * @return RedirectResponse|Response
     */
    public function categoryCreate(Request $request, BlogCategoryCreateHandler $handler, TranslatableFlashBag $flashBag)
    {
        /**@var AuthUser $userApp */
        $userApp = $this->getUser();
        $user = $userApp->getUser();

        $blogCategoryCreateDTO = new BlogCategoryCreateDTO($user->getId());
        $form = $this->createForm(BlogCategoryCreateType::class,$blogCategoryCreateDTO);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $handler->handle($data);
            $flashBag->addSuccessFlash('blog_category.create.success');

            return $this->redirectToRoute('blog_category_list');
        }

        return $this->render('admin/blog/category/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/blog/category/list", name="blog_category_list")
     * @param BlogCategoryRepositoryInterface $blogCategoryRepository
     * @return Response
     */
    public function categoryList(BlogCategoryRepositoryInterface $blogCategoryRepository)
    {
        $blogCategories = $blogCategoryRepository->getAll();

        return $this->render('admin/blog/category/list.html.twig', [
            'blogCategories' => $blogCategories
        ]);

    }

    /**
     * @Route("/admin/blog/category/{id}/delete", name="blog_category_delete")
     * @param int $id
     * @param BlogCategoryDeleteHandler $handler
     * @param TranslatableFlashBag $flashBag
     * @return RedirectResponse
     */
    public function categoryDelete(int $id, BlogCategoryDeleteHandler $handler, TranslatableFlashBag $flashBag)
    {
        /**@var AuthUser $userApp */
        $userApp = $this->getUser();
        $user = $userApp->getUser();

        try {
            $blogCategoryDeleteDTO = new BlogCategoryDeleteDTO($user->getId(),$id);
            $handler->handle($blogCategoryDeleteDTO);
            $flashBag->addSuccessFlash('blog.category.delete.success');

            return $this->redirectToRoute('blog_category_list');

        }catch (BlogCategoryExceptionNotFound $e) {
            throw new NotFoundHttpException();
        }catch (UserNotIsPropertyOfObjectException $e) {
            throw new AccessDeniedHttpException();
        }

    }

    /**
     * @Route("/admin/blog/category/{id}/update", name="blog_category_update")
     * @param Request $request
     * @param int $id
     * @param BlogCategoryRepositoryInterface $blogCategoryRepository
     * @param BlogCategoryUpdateHandler $handler
     * @param TranslatableFlashBag $flashBag
     * @return Response
     */
    public function categoryUpdate(Request $request,
                                   int $id,
                                   BlogCategoryRepositoryInterface $blogCategoryRepository,
                                   BlogCategoryUpdateHandler $handler,
                                   TranslatableFlashBag $flashBag)
    {
        /**@var AuthUser $userApp */
        $userApp = $this->getUser();
        $user = $userApp->getUser();

        try {
            $blogCategory = $blogCategoryRepository->getById($id);
            $blogCategoryUpdateDTO = BlogCategoryUpdateDTO::createByCategoryAndUserId($blogCategory,$user->getId());
            $form = $this->createForm(BlogCategoryUpdateType::class,$blogCategoryUpdateDTO);

            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()) {
                $data = $form->getData();
                $handler->handle($data);
                $flashBag->addSuccessFlash('blog.category.success.update');
                return $this->redirectToRoute('blog_category_list');
            }

            return $this->render('admin/blog/category/update.html.twig', [
                'form' => $form->createView(),
                'blogCategoryImage' => $blogCategory->getImage()
            ]);


        }catch (BlogCategoryExceptionNotFound $e) {
            throw new NotFoundHttpException();
        }catch (UserNotIsPropertyOfObjectException $e) {
            throw new AccessDeniedHttpException();
        }
    }

    /**
     * @Route("/admin/blog/post/create", name="blog_post_create")
     * @param Request $request
     * @param PostCreateHandler $handler
     * @param TranslatableFlashBag $flashBag
     * @return RedirectResponse|Response
     */
    public function postCreate(Request $request, PostCreateHandler $handler, TranslatableFlashBag $flashBag)
    {
        /**@var AuthUser $userApp */
        $userApp = $this->getUser();
        $user = $userApp->getUser();

        $postCreateDTO = new PostCreateDTO($user->getId());
        $form = $this->createForm(PostCreateType::class,$postCreateDTO);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $handler->handle($postCreateDTO);
            $flashBag->addSuccessFlash('post.create.success');

            return $this->redirectToRoute('blog_post_create');

        }

        return $this->render('admin/blog/post/create.html.twig', [
            'form' => $form->createView(),
        ]);

    }

    /**
     * @Route("/admin/blog/post/list", name="blog_post_list")
     * @param PostRepositoryInterface $postRepository
     * @return Response
     */
    public function postList(PostRepositoryInterface $postRepository)
    {
        $posts = $postRepository->getAll();

        return $this->render('admin/blog/post/list.html.twig', [
            'posts' => $posts
        ]);


    }

    /**
     * @Route("/admin/blog/post/{id}/delete", name="blog_post_delete")
     * @param int $id
     * @param PostDeleteHandler $handler
     * @param TranslatableFlashBag $flashBag
     * @return RedirectResponse
     */
    public function postDelete(int $id, PostDeleteHandler $handler, TranslatableFlashBag $flashBag)
    {
        /**@var AuthUser $userApp */
        $userApp = $this->getUser();
        $user = $userApp->getUser();

        try {
            $postDeleteDTO = new PostDeleteDTO($id,$user->getId());
            $handler->handle($postDeleteDTO);
            $flashBag->addSuccessFlash('post.delete.success');
            return $this->redirectToRoute('blog_post_list');


        }catch (PostNotFoundException $e) {
            throw new NotFoundHttpException();
        }catch (UserNotIsPropertyOfObjectException $e) {
            throw new AccessDeniedHttpException();
        }

    }

    /**
     * @Route("/admin/blog/post/{id}/update", name="blog_post_update")
     * @param Request $request
     * @param int $id
     * @param PostRepositoryInterface $postRepository
     * @param PostUpdateHandler $handler
     * @param TranslatableFlashBag $flashBag
     */
    public function postUpdate(Request $request,
                               int $id ,
                               PostRepositoryInterface $postRepository,
                               PostUpdateHandler $handler,
                               TranslatableFlashBag $flashBag)
    {
        /**@var AuthUser $userApp */
        $userApp = $this->getUser();
        $user = $userApp->getUser();

        try {
            $post = $postRepository->getById($id);
            $postUpdateDTO = PostUpdateDTO::createByPostAndUserId($post,$user->getId());
            $form = $this->createForm(PostUpdateType::class,$postUpdateDTO);

            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()) {
                $data = $form->getData();
                $handler->handle($data);
                $flashBag->addSuccessFlash('post.update.success');
                return $this->redirectToRoute('blog_post_list');

            }

        }catch (PostNotFoundException $e) {
            throw new NotFoundHttpException();
        }

        return $this->render('admin/blog/post/update.html.twig', [
            'form' => $form->createView(),
            'imageList' => $post->getImageList(),
            'imageFull' => $post->getImage()
        ]);
    }

    /**

templates/blog/category-list.html.twig
{% extends 'base.html.twig' %}


{% block title %} {{ category.metaTitle }}{% endblock %}
{% block metaDescription %} {{ category.metaDescription}} {% endblock %}
{% block slider %}
    {% include '_partials/slider/slider_blog_category.html.twig' with {'category' : category} %}
{% endblock %}
{% block body %}
    <div class="main-wrapper triangle__end--reverse">
        <div class="row blog-wrapper">
            <div class="blog-items">
        {% for post in query.result %}
            {% include '_partials/miniatures/post.html.twig' with {'post': post }  %}
        {% endfor %}
                {{ include('_partials/_pagination_category.html.twig', {query: query, categoryId: category.id , categorySlug: category.slug}) }}
        </div>
        <div class="blog-sidebar">
                <div class="blog-sidebar__item">
                    <div class="title__sidebar">
                        <h3 class="title title--lg title--secondary">Categorias</h3>
                    </div>
                    <div class="sidebar__list">
                        <ul class="sidebar__list">
                            {% for category in categoryWithPost %}
                                <li><a href="{{ path('blog_category_page',{'id': category.id, 'slug' : category.slug })  }}">{{ category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            <div class="blog-sidebar__item">
                <div class="title__sidebar">
                    <h3 class="title title--lg title--secondary">Ultimas Entradas</h3>
                </div>
                <div class="sidebar__list">
                    <ul class="sidebar__list">
                        {% for lastPost in lastPosts %}
                            <li>{{ lastPost.title }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/blog/list.html.twig
{% extends 'base.html.twig' %}


{% block title %} OSCAR SOFTWARE DEVELOPER{% endblock %}
{% block metaDescription %} Ingeniero Multimedia Alicante {% endblock %}
{% block slider %}
    {% include '_partials/slider/slider_blog.html.twig' %}
{% endblock %}
{% block body %}
    <div class="main-wrapper triangle__end--reverse">
        <div class="row blog-wrapper">
            <div class="blog-items">
        {% for post in query.result %}
            {% include '_partials/miniatures/post.html.twig' with {'post': post }  %}
        {% endfor %}
                {{ include('_partials/_pagination.html.twig', {query: query}) }}
        </div>
        <div class="blog-sidebar">
                <div class="blog-sidebar__item">
                    <div class="title__sidebar">
                        <h3 class="title title--lg title--secondary">Categorias</h3>
                    </div>
                    <div class="sidebar__list">
                        <ul class="sidebar__list">
                            {% for category in categoryWithPost %}
                                <li><a href="{{ path('blog_category_page',{'id': category.id, 'slug' : category.slug })  }}">{{ category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            <div class="blog-sidebar__item">
                <div class="title__sidebar">
                    <h3 class="title title--lg title--secondary">Ultimas Entradas</h3>
                </div>
                <div class="sidebar__list">
                    <ul class="sidebar__list">
                        {% for lastPost in lastPosts %}
                            <li>{{ lastPost.title }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}